### ISSUE TITLE
Authors' name 'consumed' if they contain accented characters

### ISSUE THREAD

**Issue by richoux** [Azzaare/StaticWebPages.jl#13]
This bug is both funny and weird: in references, if the name or the first name of an author contains x accented characters, then the last x characters in the name (or the first name, it depends what come last) are "consumed" and not displayed in the bibtex frame.

For instance: 
* Baffier, Jean-François becomes Baffier, Jean-Françoi. 
* Téletchéa, Stéphane becomes Téletchéa, Stéph

**Comment by Azzaare** [comment]
Done v0.2.1
