### ISSUE TITLE
Publications page is not fully generated if a reference name contains a dash

### ISSUE THREAD

**Issue by richoux** [Azzaare/StaticWebPages.jl#14]
Imagine I have in my bibtex:

@article{abc20,
...
}
@article{def19,
...
}
@article{ghi18-a,
...
}
@article{jkl17,
...
}

then the publications page stopped to be generated at ghi18-a (excluded). Removing the dash in the reference name fix the problem.

**Comment by Azzaare** [comment]
How does Apple say? It is not a bug, it is a feature!

Joke aside, I think the official BibTeX grammar does not accept dash in the reference name. I will add the possibility for it anyway (and add a warning if it is indeed not officially within BibTeX grammar scope.
